server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-route
          # Маршрутизация на main-service
          uri: http://main-service:8081
          predicates:
            - Path=/auth/**
        - id: main-api
          uri: http://main-service:8081
          predicates:
            - Path=/api/**, /patients/**
          filters:
            - Authentication # <--- ИСПРАВЛЕНО (было AuthenticationFilter)

eureka:
  client:
    enabled: false

application:
  jwt:
    secret: super-secret-key-that-must-be-very-long-and-secure-base64-encoded

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metrics
  zipkin:
    tracing:
      endpoint: "http://${ZIPKIN_HOST:zipkin}:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0