server:
  port: 8081

spring:
  application:
    name: main-service
  datasource:
    # Используем имя сервиса "postgres" внутри сети Docker
    url: jdbc:postgresql://postgres:5432/clinicdb
    username: clinic_user
    password: supersecret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: redis
      port: 6379

# Настройки для MinIO
application:
  minio:
    url: http://minio:9000
    access-key: minio_admin
    secret-key: minio_password
    bucket: medical-records
  jwt:
    # Тот же ключ, что и в Gateway
    secret: super-secret-key-that-must-be-very-long-and-secure-base64-encoded

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metrics
  zipkin:
    tracing:
      endpoint: "http://${ZIPKIN_HOST:zipkin}:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0

eureka:
  client:
    enabled: false