server:
  port: 8081

spring:
  datasource:
    # ИСПРАВЛЕНО: Порт изменен на 5433, чтобы совпадать с Docker Compose
    url: jdbc:postgresql://${DB_HOST:localhost}:5433/clinicdb
    username: clinic_user
    password: supersecret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

application:
  minio:
    url: http://${MINIO_HOST:localhost}:9000
    access-key: minio_admin
    secret-key: minio_password
    bucket: medical-records
  jwt:
    secret: super-secret-key-that-must-be-very-long-and-secure-base64-encoded

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metrics
  zipkin:
    tracing:
      endpoint: "http://${ZIPKIN_HOST:zipkin}:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0